In [3]:
import pandas as pd

stock_dict = {
  'Items': ["Sugar", "Salt", "Pepper"],
  'Qunatity(Kgs)': [10, 20, 5]
}

stock_df = pandas.DataFrame(stock_dict)

print(stock_df)

    Items  Qunatity(Kgs)
0   Sugar             10
1    Salt             20
2  Pepper              5


In [4]:

quantity = [10, 20, 30]

quantity_series = pd.Series(quantity)

print(quantity_series)

0    10
1    20
2    30
dtype: int64


In [5]:
quantity = [10, 20, 30]

quantity_series = pd.Series(quantity, index = ["Sugar", "Salt", "Pepper"])

print(quantity_series["Sugar"])

10


In [6]:
pantry={'eggs':10,'butter(tbsp)':20,'sugar(oz)':30,'salt(oz)':40}

pantry_series = pd.Series(pantry)
print(pantry_series)
pantry_series_slice = pd.Series(pantry, index = ['eggs', 'butter(tbsp)'])
print(pantry_series_slice)

eggs            10
butter(tbsp)    20
sugar(oz)       30
salt(oz)        40
dtype: int64
eggs            10
butter(tbsp)    20
dtype: int64


In [7]:
data = {
  "quantity_available": [420, 380, 390],
  "quantity_needed_for_full_inventory": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

   quantity_available  quantity_needed_for_full_inventory
0                 420                                  50
1                 380                                  40
2                 390                                  45


In [8]:
print(df.loc[0]) # returns single row
print(df.loc[[0, 1]]) # returns multiple rows in a dataframe

quantity_available                    420
quantity_needed_for_full_inventory     50
Name: 0, dtype: int64
   quantity_available  quantity_needed_for_full_inventory
0                 420                                  50
1                 380                                  40


In [9]:
data = {
  "quantity_available": [420, 380, 390],
  "quantity_needed_for_full_inventory": [50, 40, 45]
}

#load data into a DataFrame object:
df_labeled = pd.DataFrame(data, index = ['Sugar', 'Salt', 'Pepper'])

print(df_labeled) 

        quantity_available  quantity_needed_for_full_inventory
Sugar                  420                                  50
Salt                   380                                  40
Pepper                 390                                  45


In [10]:
print(df_labeled.loc['Sugar'])
print(df_labeled.loc[['Sugar','Salt']])

quantity_available                    420
quantity_needed_for_full_inventory     50
Name: Sugar, dtype: int64
       quantity_available  quantity_needed_for_full_inventory
Sugar                 420                                  50
Salt                  380                                  40


In [11]:
data = {
  "quantity_available": [5, 10, 15, 20, 25, 30, 35, 12, 10, 10, 25, 15],
  "quantity_needed_for_full_inventory": [50, 40, 45, 60, 60, 80, 100, 50, 25, 50, 50, 30],
  "Name_of_item":['Sugar','Salt','Pepper','Butter','Flour','Baking Powder','eggs','Blue Cheese', 'Panko', 'Maple Syrup', 'Strawberry Preserve', 'Honey']
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df.head())
print(df.tail())

print(df.head(10))
print(df.tail(10))

   quantity_available  quantity_needed_for_full_inventory Name_of_item
0                   5                                  50        Sugar
1                  10                                  40         Salt
2                  15                                  45       Pepper
3                  20                                  60       Butter
4                  25                                  60        Flour
    quantity_available  quantity_needed_for_full_inventory  \
7                   12                                  50   
8                   10                                  25   
9                   10                                  50   
10                  25                                  50   
11                  15                                  30   

           Name_of_item  
7           Blue Cheese  
8                 Panko  
9           Maple Syrup  
10  Strawberry Preserve  
11                Honey  
   quantity_available  quantity_needed_for_fu

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                              Non-Null Count  Dtype 
---  ------                              --------------  ----- 
 0   quantity_available                  12 non-null     int64 
 1   quantity_needed_for_full_inventory  12 non-null     int64 
 2   Name_of_item                        12 non-null     object
dtypes: int64(2), object(1)
memory usage: 416.0+ bytes
None


# Numpy

In [13]:
import numpy 

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
arr = np.array(42)

print(arr)

42


In [16]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:


arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [20]:
print(arr.ndim)

5


In [21]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1:5]) # Slice elements from index 1 to index 5
print(arr[4:]) # Slice elements from index 4 to the end of the array
print(arr[:4]) # Slice elements from the beginning to index 4 (not included)
print(arr[-3:-1]) # Slice from the index 3 from the end to index 1 from the end
print(arr[1:5:2]) # Return every other element from index 1 to index 5
print(arr2[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included)
print(arr2[0:2, 1:4]) # From both elements, slice index 1 to index 4 (not included)

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[7 8 9]
[[2 3 4]
 [7 8 9]]


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [28]:


arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [29]:


arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [31]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]
